import subprocess
subprocess.run(["pip","install","click"])
subprocess.run(["pip","install","unidecode"])
print("CESAR NO KEY DECRYPTION")
print("Short Text to Decrypt:")
subprocess.run(["python", "Lab1-Vernam&Cesar\Cesar\DemoShortKey.py"])
print("Finished Sort Text")
print("Long Text to Decrypt:")
subprocess.run(["python", "Lab1-Vernam&Cesar\Cesar\DemoLongKey.py"])
print("Finished Long Text and Cesar\n")
print("VERNAM NO KEY DECRYPTION")
print("Finding key of length 2 [la]:")
subprocess.run(["python", "Lab1-Vernam&Cesar/Vernam/TestKeyLength2.py"])
print("Finished key length 2 \n")
print("Finding key of length 3 [lim]:")
subprocess.run(["python", "Lab1-Vernam&Cesar/Vernam/TestKeyLength3.py"])
print("Finished key length 3 \n")
print("Finding key of length 4 [huir]:")
subprocess.run(["python", "Lab1-Vernam&Cesar/Vernam/TestKeyLength4.py"])
print("Finished key length 4 \n")
