import VernamNoKey
import utilities
if __name__ == '__main__':
    text = "iamgoingtodoitihavemadeupmymindthesearethefirstfewwordsofthenewthebestthelongesttextintheentirehistoryoftheknownuniversethishastohaveover35000wordsthebeatthecurrentworldrecordsetbythatpersonwhomadethatflamingchickenhandbookythingyimightjustbesayingrandomthingsthewholetimeitypeinthissoyoumightgetconfusedalotijustdiscoveredsomethingterribleautocorrectisonnothishastobecrazysoiwillhavetobreakalltheenglishlanguagerulesandthebasicknowledgeoftheaveragehumanbeingiamnotanaveragehumanbeinghoweveriamspecialnonononotthatkindofspecialwhydopeoplesendthatwinkfaceitalwaysgivesmenightmaresitcanmakeacompletelynormalsentencecreepyimagineyouaregoingtoafriendshousesoyoutextthisseeyousoonseemsnormalrightbutwhatisyouaddthewordsemitothatcolonisthatrightorisittheotherwayaroundwhatisyouaddalorrytothatbriquettessemitrucktothatcoalonanywaybacktothepointseeyousoonthatisjustsocreepyisthatreallyyourfriendorisitacreepystalkerwatchingyoureverymoveorevenworseisityourfriendwhoisacreepystalkermaybeyouthoughtitwasyourfriendbutitwasactuallyyourfriendletmeexplainyouarehappilyinmcdonaldsgettingfatwhileeatingyummyfoodandsomerandomdudewalksupandblotsoutthesunhelookslikearegularhereyoucantseeanythingelsethanhimsoyoucanttrytoavoideyecontacthefinisheseatinghischeeseburgermorelikehorseburgherilearnedthatwordfromthemerchantofvenicewhichisagoodplayifyoucanunderstanditicancauseigotaspecialbookwithallthewordsinreadableenglishwrittenonthesideofthepagewhichiskindafunnybecauseshakespearewassupposedtobeagoodpoetbutnoonecanunderstandhimandhesracistinact2scene1oftheplaytooandsitsdownbesideyoulikeyouareoldpalsyouvenevermethimbeforebuthelookslikehecouldbeinsomeweirdcultheclearshisthroatandasksyouaverypersonalquestioncanihavesomefrenchfriesidontknowwhytherecalledfrenchfrieswheniveneverseenafrenchpersoneatfriesalltheyeatitisstufflikebaguettesandcrpesandratsnamedrattytwoeewhichisareallyfungameontheplaystation2andyouthinkbubblycloudthinkingbubblehahahahahhahahahahahahahaha"
    text = utilities.removeDiacritics(text)
    text = utilities.sanitizeToAlpha(text)
    plain_text = text.encode("utf-8") 
    key = "lim"
    ciphered_text,key = VernamNoKey.EncryptDecrypt.vernam(plain_text,key)
    gcd = VernamNoKey.CalculateKey(ciphered_text)
    Keys = VernamNoKey.ShowKeys(gcd,text,ciphered_text)
    if len(Keys) == 0:
        VernamNoKey.add_keys_to_AllKeys(VernamNoKey.ShowKeys(gcd -1,text,ciphered_text),Keys)
        VernamNoKey.add_keys_to_AllKeys(VernamNoKey.ShowKeys(gcd +1,text,ciphered_text),Keys)
